# action.yml
name: "Gemini Review Bot"
description: "Review Pull Requests using Gemini"
branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  GEMINI_API_KEY:
    description: "Gemini API Key"
    required: true
    default: ""
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  MODEL_CODE:
    description: "Model code for Gemini"
    default: "models/gemini-2.5-flash"
  LANGUAGE:
    description: "Preferred language for review comments"
    default: "English"
  EXCLUDE_PATHS:
    description: "Patterns to exclude from review (comma-separated)"
    required: false
    default: ""
  USE_SINGLE_COMMENT_REVIEW:
    description: "Use single comment review instead of line-by-line comments"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: cd ${GITHUB_ACTION_PATH} && npm install
      shell: bash

    - name: Run review bot
      run: cd ${GITHUB_ACTION_PATH} && node dist/index.js
      shell: bash
      env:
        GOOGLE_GENERATIVE_AI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.pull_request.head.repo.name }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        LANGUAGE: ${{ inputs.LANGUAGE }}
        MODEL_CODE: ${{ inputs.MODEL_CODE }}
        EXCLUDE_PATHS: ${{ inputs.EXCLUDE_PATHS }}
        USE_SINGLE_COMMENT_REVIEW: ${{ inputs.USE_SINGLE_COMMENT_REVIEW }}
